#!/bin/bash
echo "================================================"
echo "  Add Entitlements File to Widget Extension"
echo "================================================"
echo ""
echo "The entitlements file has been created at:"
echo "  InformedWidget/InformedWidget.entitlements"
echo ""
echo "Now you need to add it to the Xcode project:"
echo ""
echo "1. Open informed.xcodeproj in Xcode"
echo "2. Select 'InformedWidgetExtension' target"
echo "3. Go to 'Signing & Capabilities' tab"
echo "4. Under 'Signing' section, look for 'Entitlements File'"
echo "5. Set it to: InformedWidget/InformedWidget.entitlements"
echo ""
echo "OR"
echo ""
echo "1. In Xcode, right-click 'InformedWidget' folder in Project Navigator"
echo "2. Select 'Add Files to informed...'"
echo "3. Navigate to and select 'InformedWidget.entitlements'"
echo "4. Make sure 'InformedWidgetExtension' target is checked"
echo "5. Click 'Add'"
echo ""
echo "Then rebuild and run on your device."
echo ""
echo "================================================"
